
import Conexion.JdbcOra;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author User
 */
public class Gui_Producto extends javax.swing.JFrame {

    /**
     * Creates new form Gui_Producto
     */
    String[] registra;
    int subTotal = 0;
    int iva = 0;
    int total = 0;
    String nombre = "";
    DefaultTableModel modelo;

    public Gui_Producto() {
        initComponents();

        String[] titulos = {"Codigo", "Nombre", "Cantidad"};
        modelo = new DefaultTableModel(null, titulos);
        this.jTable1.setModel(modelo);
        registra = new String[3];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pro_codigo = new javax.swing.JTextField();
        pro_descripcion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Codigo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Descripcion");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 136, -1, -1));
        getContentPane().add(pro_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 100, 179, -1));
        getContentPane().add(pro_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 140, 179, -1));

        jLabel4.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("REGISTRAR PRODUCTOS");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Grabar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 486, 160));

        jButton2.setText("Actualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        jButton3.setText("Mostrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 428, 94, -1));

        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 99, -1, -1));

        jButton5.setText("Cerrar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 519, -1, -1));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mostrar todos los productos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 424, -1, -1));

        jLabel5.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mostrar productos cantidad cero(0)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 477, -1, -1));

        jButton6.setText("Mostrar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 481, 94, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // CREAR PRODUCTOS
        JdbcOra conexionOracle = new JdbcOra();

        //ConexionMySQL mysql = new ConexionMySQL();
        //Connection cn = mysql.Conectar();
        int pCodigo = 0;
        String pDescripcion = "";
        int cantidad = 0;

        String SQL = ""; // PARA CREAR EL INTO PARA INSERTAR DATOS EN LA BASE DE DATOS
        String mensaje = "";
        pCodigo = Integer.parseInt(this.pro_codigo.getText());
        pDescripcion = this.pro_descripcion.getText();

        SQL = "INSERT INTO productos (CODPROD,DESCRIPCION,SALDPROD) VALUES (?,?,?)";
        mensaje = "el registro ha sido exitoso";

        try {

            conexionOracle.conectar();
            Connection conn = conexionOracle.getConnection();
            Statement stmt = conn.createStatement();

            PreparedStatement pst = conn.prepareStatement(SQL);

            pst.setInt(1, pCodigo);
            pst.setString(2, pDescripcion);
            pst.setInt(3, cantidad);

            int n = pst.executeUpdate();

            
            
            conn.commit();

            if (n > 0) {
                JOptionPane.showMessageDialog(null, mensaje);
            }

            stmt.close();
            conexionOracle.cerrar();

        } catch (SQLException e) {
            Object ex = null;
            JOptionPane.showMessageDialog(null, ex);
        }

        this.pro_codigo.setText(null);
        this.pro_descripcion.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        
        JdbcOra conexionOracle = new JdbcOra();
        
        String[] titulos = {"Codigo", "Nombre", "Cantidad"};
        String[] registra = new String[3];
        String sSQL = "";

        DefaultTableModel modelo = new DefaultTableModel(null, titulos);

        //ConexionMySQL mysql = new ConexionMySQL();
        //Connection cn = mysql.Conectar();

        sSQL = "Select * from productos";

        try {
            
            conexionOracle.conectar();
            Connection conn = conexionOracle.getConnection();
            Statement stmt = conn.createStatement();

            ResultSet rs = stmt.executeQuery(sSQL);

            while (rs.next()) {

                registra[0] = rs.getString("CODPROD");
                registra[1] = rs.getString("DESCRIPCION");
                registra[2] = rs.getString("SALDPROD");

                modelo.addRow(registra);
            }

            this.jTable1.setModel(modelo);
            
            conn.commit();
            
            stmt.close();
            conexionOracle.cerrar();

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new Menu().setVisible(rootPaneCheckingEnabled);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        // ACTUALIZAR PRODUCTOS
        JdbcOra conexionOracle = new JdbcOra();

      
        //declarar las variables de los campos de la tablas       
        String vNombre = "";


        //variable para la sentencia sql
        String ssSQL = "";
        //variable para mostrar si se actualizaron los datos
        String mensaje = "";

        vNombre = pro_descripcion.getText();

        ssSQL = "update productos "
                + "Set DESCRIPCION=? "
                + " where CODPROD='" + this.pro_codigo.getText() + "'";

        mensaje = "Registro guardado con exito!!";

        try {
            conexionOracle.conectar();
            Connection conn = conexionOracle.getConnection();
            Statement stmt = conn.createStatement();

            PreparedStatement pst = conn.prepareStatement(ssSQL);
            pst.setString(1, vNombre);


            conn.commit();

            int n = pst.executeUpdate();

            if (n > 0) {

                JOptionPane.showMessageDialog(null, mensaje);
            }

            stmt.close();
            conexionOracle.cerrar();
        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        // BUSCAR PRODUCTO
        JdbcOra conexionOracle = new JdbcOra();

        String sSQL = "";
        //ConexionMySQL mysql = new ConexionMySQL();
        //Connection cn = mysql.Conectar();

        sSQL = "Select * from productos where CODPROD='" + this.pro_codigo.getText() + "'";

        try {

            conexionOracle.conectar();
            Connection conn = conexionOracle.getConnection();
            Statement stmt = conn.createStatement();

            ResultSet rs = stmt.executeQuery(sSQL);

            if (rs.next() == true) {

                // se entrega el campo de activo a la variable activo
                //condicional para no mostrar los datos si esta inactivo el cliente
                // si el cliente esta activo entra en la condicional 
                this.pro_descripcion.setText(rs.getString("DESCRIPCION"));

            } else {
                JOptionPane.showMessageDialog(null, "Producto no existe");
            }

            conn.commit();

            stmt.close();
            conexionOracle.cerrar();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        
        JdbcOra conexionOracle = new JdbcOra();
        
        String[] titulos = {"Codigo", "Nombre", "Cantidad"};
        String[] registra = new String[3];
        String sSQL = "";

        DefaultTableModel modelo = new DefaultTableModel(null, titulos);

        //ConexionMySQL mysql = new ConexionMySQL();
        //Connection cn = mysql.Conectar();

        sSQL = "Select * from productos";

        try {
            
            conexionOracle.conectar();
            Connection conn = conexionOracle.getConnection();
            Statement stmt = conn.createStatement();

            ResultSet rs = stmt.executeQuery(sSQL);

            while (rs.next()) {

                registra[0] = rs.getString("CODPROD");
                registra[1] = rs.getString("DESCRIPCION");
                registra[2] = rs.getString("SALDPROD");
                
                if(Integer.parseInt(rs.getString("SALDPROD")) < 1){
                 
                    modelo.addRow(registra);
                    
                }

                
            }

            this.jTable1.setModel(modelo);
            
            conn.commit();
            
            stmt.close();
            conexionOracle.cerrar();

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui_Producto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField pro_codigo;
    private javax.swing.JTextField pro_descripcion;
    // End of variables declaration//GEN-END:variables
}
