
import Conexion.JdbcOra;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Gui_ListaPrecios extends javax.swing.JFrame {

    /**
     * Creates new form Gui_ListaPrecios
     */
    public Gui_ListaPrecios() {
        initComponents();
        
        JdbcOra conexionOracle = new JdbcOra();
        
        this.jComboBox1.removeAllItems();
   
  
        String SQLproductos = "";

        SQLproductos = "Select * from productos";

        try {

            
            conexionOracle.conectar();
            Connection conn = conexionOracle.getConnection();
            Statement stmt = conn.createStatement();

            ResultSet rs = stmt.executeQuery(SQLproductos);
           
            while (rs.next()) {
                this.jComboBox1.addItem(rs.getString("DESCRIPCION"));
            }
            
           conn.commit();

            stmt.close();
            conexionOracle.cerrar();         
            

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 164, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lista Precios");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 29, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Producto");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 90, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Precio Compra");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 100, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Precio Venta");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 100, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Actualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 130, 30));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Cerrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
// BUSCAR PRODUCTO

        JdbcOra conexionOracle = new JdbcOra();

        String sSQL = "";
        int CodProducto = 0;

        sSQL = "Select * from PRODUCTOS where DESCRIPCION='" + this.jComboBox1.getSelectedItem() + "'";

        try {

            conexionOracle.conectar();
            Connection conn = conexionOracle.getConnection();
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sSQL);

            //Statement st = cn.createStatement();
            //ResultSet rs = st.executeQuery(sSQL);
            if (rs.next() == true) {

                // se entrega el campo de activo a la variable activo
                //condicional para no mostrar los datos si esta inactivo el cliente
                // si el cliente esta activo entra en la condicional 
                CodProducto = Integer.parseInt(rs.getString("CODPROD"));

            }

            stmt.close();
            conexionOracle.cerrar();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

        // TRAE LOS PRECIOS DE LOS PRODUCTOS
        String SQL = "Select * from LISTAPRECIOS where CODPROD='" + CodProducto + "'";

        try {

            conexionOracle.conectar();
            Connection conn = conexionOracle.getConnection();
            Statement stmt = conn.createStatement();
            ResultSet rs1 = stmt.executeQuery(SQL);

            //Statement st = cn.createStatement();
            //ResultSet rs = st.executeQuery(sSQL);
            if (rs1.next() == true) {

                // se entrega el campo de activo a la variable activo
                //condicional para no mostrar los datos si esta inactivo el cliente
                // si el cliente esta activo entra en la condicional 
                this.jTextField1.setText(rs1.getString("COSTO"));
                this.jTextField2.setText(rs1.getString("PRECIOVTA"));

            }

            stmt.close();
            conexionOracle.cerrar();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        
        // GRABAR LISTA PRECIOS Y ACTUALIZAR
        
        JdbcOra conexionOracle = new JdbcOra();

        String vNombre = "";
        String vCiudad = "";
        String SQLactualizar = "";
        String SQLselectListaPrecios = "";
        String mensaje = "el registro ha sido exitoso";

        String sSQL = "";
        String SQLlistaPrecios = "";
        int CodProducto = 0;

        sSQL = "Select * from PRODUCTOS where DESCRIPCION='" + this.jComboBox1.getSelectedItem() + "'";
        SQLlistaPrecios = "INSERT INTO LISTAPRECIOS (CODPROD,COSTO,PRECIOVTA) VALUES (?,?,?)";
        

        try {

            conexionOracle.conectar();
            Connection conn = conexionOracle.getConnection();
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sSQL);

            //Statement st = cn.createStatement();
            //ResultSet rs = st.executeQuery(sSQL);
            if (rs.next() == true) {

                // se entrega el campo de activo a la variable activo
                //condicional para no mostrar los datos si esta inactivo el cliente
                // si el cliente esta activo entra en la condicional 
                CodProducto = Integer.parseInt(rs.getString("CODPROD"));

                               
                SQLselectListaPrecios = "Select * from LISTAPRECIOS where CODPROD='" + CodProducto+ "'";
                
                
                ResultSet rs3 = stmt.executeQuery(SQLselectListaPrecios);
                if (rs3.next() != true) {

                    vNombre = this.jTextField1.getText();
                    vCiudad = this.jTextField2.getText();

                    PreparedStatement pst1 = conn.prepareStatement(SQLlistaPrecios);
                    pst1.setInt(1, CodProducto);
                    pst1.setString(2, vNombre);
                    pst1.setString(3, vCiudad);

                    int n = pst1.executeUpdate();
                    conn.commit();
                    if (n > 0) {
                        JOptionPane.showMessageDialog(null, mensaje);

                    }
                } else {

                    vNombre = this.jTextField1.getText();
                    vCiudad = this.jTextField2.getText();

                    SQLactualizar = "update LISTAPRECIOS "
                            + "Set COSTO=?, "
                            + "PRECIOVTA=? "
                            + " where CODPROD='" + CodProducto + "'";

                    PreparedStatement pst2 = conn.prepareStatement(SQLactualizar);
                    pst2.setString(1, vNombre);
                    pst2.setString(2, vCiudad);

                    conn.commit();

                    int n = pst2.executeUpdate();

                    if (n > 0) {

                        JOptionPane.showMessageDialog(null, mensaje);
                    }
                }
            }

            stmt.close();
            conexionOracle.cerrar();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new Menu().setVisible(rootPaneCheckingEnabled);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui_ListaPrecios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui_ListaPrecios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui_ListaPrecios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui_ListaPrecios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui_ListaPrecios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
