/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import Conexion.JdbcOra;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Gui_Proveedores extends javax.swing.JFrame {

    /**
     * Creates new form Gui_Proveedores
     */
    String[] registra;
    int subTotal = 0;
    int iva = 0;
    int total = 0;
    String nombre = "";
    DefaultTableModel modelo;

    public Gui_Proveedores() {
        initComponents();

        String[] titulos = {"Nit", "Nombre", "Ciudad", "Telefono", "Email"};
        modelo = new DefaultTableModel(null, titulos);
        this.jTable1.setModel(modelo);
        registra = new String[5];

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nit");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ciudad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Telefono");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contacto");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 100, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 260, -1));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 80, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 100, -1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 260, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Creación Proveedores");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 26, -1, 30));

        jButton2.setText("Actualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 347, 381, 122));

        jButton3.setText("Listar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 306, -1, -1));

        jButton4.setText("Mostrar Proveedores");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 140, -1));

        jButton5.setText("Cerrar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 480, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        JdbcOra conexionOracle = new JdbcOra();
        
        
        
        
        //ConexionMySQL mysql = new ConexionMySQL();
        //Connection cn = mysql.Conectar();

        int vNit = 0;
        String vNombre = "";
        String vCiudad = "";
        String vTelefono = "";
        String vContacto = "";

        String SQL = ""; // PARA CREAR EL INTO PARA INSERTAR DATOS EN LA BASE DE DATOS
        String mensaje = "";
        vNit = Integer.parseInt(this.jTextField1.getText());
        vNombre = this.jTextField2.getText();
        vCiudad = this.jTextField3.getText();
        vTelefono = this.jTextField4.getText();
        vContacto = this.jTextField5.getText();

        SQL = "INSERT INTO proveedor (NIT,DESCRIPCION,DIRECCION,CONTACTO,TELEFONO) VALUES (?,?,?,?,?)";
        mensaje = "el registro ha sido exitoso";

        try {
            
            conexionOracle.conectar();
            Connection conn = conexionOracle.getConnection();
            Statement stmt = conn.createStatement();

            PreparedStatement pst = conn.prepareStatement(SQL);
            pst.setInt(1, vNit);
            pst.setString(2, vNombre);
            pst.setString(3, vCiudad);
            pst.setString(4, vContacto);
            pst.setString(5, vTelefono);
            
            int n = pst.executeUpdate();
            conn.commit();
            if (n > 0) {
                JOptionPane.showMessageDialog(null, mensaje);
            }

            
            stmt.close();
            conexionOracle.cerrar();
        } catch (SQLException e) {
            Object ex = null;
            JOptionPane.showMessageDialog(null, ex);

        }

        this.jTextField1.setText(null);
        this.jTextField2.setText(null);
        this.jTextField3.setText(null);
        this.jTextField4.setText(null);
        this.jTextField5.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        
        JdbcOra conexionOracle = new JdbcOra();
        
        String[] titulos = {"Nit", "Descripcion", "Direccion", "Contacto", "Telefono"};
        String[] registra = new String[5];
        String sSQL = "";

        DefaultTableModel modelo = new DefaultTableModel(null, titulos);

        //ConexionMySQL mysql = new ConexionMySQL();
        //Connection cn = mysql.Conectar();
        

        sSQL = "Select * from proveedor ";

        try {
            
            conexionOracle.conectar();
            Connection conn = conexionOracle.getConnection();
            Statement stmt = conn.createStatement();
            
            //Statement st = cn.createStatement();
            ResultSet rs = stmt.executeQuery(sSQL);

            while (rs.next()) {

                registra[0] = rs.getString("NIT");
                registra[1] = rs.getString("DESCRIPCION");
                registra[2] = rs.getString("DIRECCION");
                registra[3] = rs.getString("CONTACTO");
                registra[4] = rs.getString("TELEFONO");

                modelo.addRow(registra);
            }

            this.jTable1.setModel(modelo);

            
            stmt.close();
            conexionOracle.cerrar();  
            
        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(null, ex);

        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        // BUSCAR PROVEEDORES
        
        JdbcOra conexionOracle = new JdbcOra();
        
             
        String sSQL = "";      
       

        sSQL = "Select * from proveedor where NIT='" + Integer.parseInt(this.jTextField1.getText()) + "'";

        try {
           
            conexionOracle.conectar();
            Connection conn = conexionOracle.getConnection();
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sSQL);
            
            //Statement st = cn.createStatement();
            //ResultSet rs = st.executeQuery(sSQL);

            if (rs.next()== true) {

                // se entrega el campo de activo a la variable activo
                //condicional para no mostrar los datos si esta inactivo el cliente
                // si el cliente esta activo entra en la condicional 
                this.jTextField2.setText(rs.getString("DESCRIPCION"));
                this.jTextField3.setText(rs.getString("DIRECCION"));
                this.jTextField4.setText(rs.getString("CONTACTO"));
                this.jTextField5.setText(rs.getString("TELEFONO"));

            } else {
                
                this.jTextField2.setText("");
                this.jTextField3.setText("");
                this.jTextField4.setText("");
                this.jTextField5.setText("");
                JOptionPane.showMessageDialog(null, "Proveedor no existe");
                
            }
            
            stmt.close();
            conexionOracle.cerrar();  
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        
        // ACTUALIZAR CLIENTES
        
        JdbcOra conexionOracle = new JdbcOra();
        
        
        //ConexionMySQL mysql = new ConexionMySQL();
        //Connection cn = mysql.Conectar();

        //declarar las variables de los campos de la tablas       
        

        //variable para la sentencia sql
        String ssSQL = "";
        //variable para mostrar si se actualizaron los datos
        int vNit = 0;
        String vNombre = "";
        String vCiudad = "";
        String vTelefono = "";
        String vEmail = "";

        
        String mensaje = "";
        vNit = Integer.parseInt(this.jTextField1.getText());
        vNombre = this.jTextField2.getText();
        vCiudad = this.jTextField3.getText();
        vTelefono = this.jTextField4.getText();
        vEmail = this.jTextField5.getText();

        
        
        ssSQL = "update proveedor "
                + "Set DESCRIPCION=?, "
                + "DIRECCION=?, "
                + "CONTACTO=?, "
                + "TELEFONO=? "
                + " where NIT='" + this.jTextField1.getText() + "'";

        mensaje = "Registro guardado con exito!!";

        try {
            conexionOracle.conectar();
            Connection conn = conexionOracle.getConnection();
            Statement stmt = conn.createStatement();
            
                   
            PreparedStatement pst = conn.prepareStatement(ssSQL);

            pst.setString(1, vNombre);
            pst.setString(2, vCiudad);
            pst.setString(3, vTelefono);
            pst.setString(4, vEmail);
            
            int n = pst.executeUpdate();

            if (n > 0) {

                JOptionPane.showMessageDialog(null, mensaje);
            }
            stmt.close();
            conexionOracle.cerrar();  
        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(null, ex);
        }     
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       new Menu().setVisible(rootPaneCheckingEnabled);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui_Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui_Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui_Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui_Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui_Proveedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
